artifacts_root: artifacts

# For data ingestion
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/emmarex/plantdisease
  raw_dataset_dir: artifacts/data_ingestion/raw_dataset
  dataset_dir: artifacts/data_ingestion/dataset

# For prepare base model
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5

# For prepare callbacks
prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5


# For training
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5


# For evaluation
evaluation:
  evaluation_score_path: artifacts/training/scores.json